package com.networkers.eventfee;
import com.networkers.notification.NotificationService;import com.networkers.user.*;import jakarta.persistence.EntityNotFoundException;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.*;import java.util.*;
@Service public class EventFeeService{
 public static final BigDecimal MONTHLY_FEE=new BigDecimal("2100.00");private final EventFeeRepository fees;private final UserRepository users;private final NotificationService notifications;
 public EventFeeService(EventFeeRepository f,UserRepository u,NotificationService n){fees=f;users=u;notifications=n;}
 @Transactional public List<EventFee> list(int year,int month){ensure(year,month);return fees.findByYearAndMonthOrderByUserFullNameAsc(year,month);}
 @Transactional public EventFee status(Long id,EventFeeStatus status){EventFee fee=fees.findById(id).orElseThrow(()->new EntityNotFoundException("Event fee record not found"));fee.setStatus(status);EventFee saved=fees.save(fee);notifications.notify(fee.getUser(),"Event fee status updated","Your event fee for "+Month.of(fee.getMonth())+" "+fee.getYear()+" is now "+status+".");return saved;}
 @Transactional public void remind(Long id){EventFee fee=fees.findById(id).orElseThrow(()->new EntityNotFoundException("Event fee record not found"));if(fee.getStatus()==EventFeeStatus.PAID)throw new IllegalStateException("This member has already paid");send(fee);}
 @Transactional public int remindAll(int year,int month){ensure(year,month);List<EventFee> unpaid=fees.findByYearAndMonthAndStatus(year,month,EventFeeStatus.UNPAID);unpaid.forEach(this::send);return unpaid.size();}
 @Scheduled(cron="0 0 9 * * *",zone="Asia/Kolkata") @Transactional public void scheduledReminders(){LocalDate today=LocalDate.now(ZoneId.of("Asia/Kolkata"));if(today.getDayOfMonth()<1||today.getDayOfMonth()>7)return;ensure(today.getYear(),today.getMonthValue());fees.findByYearAndMonthAndStatus(today.getYear(),today.getMonthValue(),EventFeeStatus.UNPAID).stream().filter(f->!today.equals(f.getLastReminderDate())).forEach(this::send);}
 private void ensure(int year,int month){if(month<1||month>12)throw new IllegalArgumentException("Invalid month");Set<Long> existing=fees.findByYearAndMonthOrderByUserFullNameAsc(year,month).stream().map(f->f.getUser().getId()).collect(java.util.stream.Collectors.toSet());List<EventFee> missing=new ArrayList<>();for(User user:users.findAllBillableMembers())if(!existing.contains(user.getId())){EventFee fee=new EventFee();fee.setUser(user);fee.setYear(year);fee.setMonth(month);fee.setAmount(MONTHLY_FEE);fee.setStatus(EventFeeStatus.UNPAID);missing.add(fee);}if(!missing.isEmpty())fees.saveAllAndFlush(missing);}
 private void send(EventFee fee){String period=Month.of(fee.getMonth()).toString().toLowerCase()+" "+fee.getYear();notifications.notify(fee.getUser(),"Monthly event fee reminder","Your Rs 2,100 event fee for "+period+" is unpaid. Please complete payment by the 7th.");fee.setLastReminderDate(LocalDate.now(ZoneId.of("Asia/Kolkata")));fees.save(fee);}
}
