import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { ArrowUp, Download, Heart, ImagePlus, MessageCircle, Pencil, Plus, Trash2, Users, X } from "lucide-react";
import { communityApi } from "../../api/communityApi";
import { useAuth } from "../../context/AuthContext.jsx";
import EmptyState from "../../components/EmptyState.jsx";

export default function CommunityFeed(){
  const {user}=useAuth();
  const[params,setParams]=useSearchParams();const meetingId=params.get("meetingId");const completion=params.get("completion");
  const[posts,setPosts]=useState([]);const[comments,setComments]=useState({});const[loading,setLoading]=useState(true);
  const[composer,setComposer]=useState({caption:completion?`Monthly one-to-one group completed at ${completion}%.`:"",file:null});const[publishing,setPublishing]=useState(false);const[composerOpen,setComposerOpen]=useState(Boolean(meetingId));
  const[yourPosts,setYourPosts]=useState(false);const[editing,setEditing]=useState(null);const[kudosPending,setKudosPending]=useState(new Set());const[likers,setLikers]=useState(null);const[downloading,setDownloading]=useState(new Set());
  const load=()=>communityApi.all().then(v=>setPosts(Array.isArray(v)?v:[])).catch(()=>setPosts([])).finally(()=>setLoading(false));
  useEffect(()=>{load()},[]);useEffect(()=>{if(meetingId)setComposerOpen(true)},[meetingId]);
  const visiblePosts=useMemo(()=>yourPosts?posts.filter(p=>String(p.author.id)===String(user?.id)):posts,[posts,yourPosts,user?.id]);
  async function kudos(id){
    if(kudosPending.has(id))return;
    const previous=posts.find(p=>p.id===id);if(!previous)return;
    setKudosPending(s=>new Set(s).add(id));
    const currentMember={id:user.id,name:user.fullName,avatar:user.profileImage,businessName:user.businessName};
    setPosts(items=>items.map(p=>p.id===id?{...p,kudosGiven:!p.kudosGiven,kudosCount:Math.max(0,p.kudosCount+(p.kudosGiven?-1:1)),kudosMembers:p.kudosGiven?(p.kudosMembers||[]).filter(member=>String(member.id)!==String(user.id)):[...(p.kudosMembers||[]),currentMember]}:p));
    try{const updated=await communityApi.kudos(id);setPosts(items=>items.map(p=>p.id===id?updated:p))}catch(e){setPosts(items=>items.map(p=>p.id===id?previous:p));toast.error(e.response?.data?.message||"Could not update kudos")}finally{setKudosPending(s=>{const n=new Set(s);n.delete(id);return n})}
  }
  async function comment(e,id){e.preventDefault();const value=comments[id]?.trim();if(!value)return;try{const added=await communityApi.comment(id,value);setComments(v=>({...v,[id]:""}));setPosts(items=>items.map(p=>p.id===id?{...p,comments:[...(p.comments||[]),added]}:p))}catch(error){toast.error(error.response?.data?.message||"Could not comment")}}
  async function publish(e){e.preventDefault();if(meetingId&&!composer.file)return toast.error("A completed meeting post requires a photo or video");const body=new FormData();body.append("caption",composer.caption);if(meetingId)body.append("meetingId",meetingId);if(composer.file)body.append("file",composer.file);setPublishing(true);try{const created=await communityApi.create(body);setPosts(items=>[created,...items]);setComposer({caption:"",file:null});setParams({});setComposerOpen(false);toast.success(meetingId?"Meeting completion post published":"Post published")}catch(error){toast.error(error.response?.data?.message||"Could not publish post")}finally{setPublishing(false)}}
  async function saveEdit(e){e.preventDefault();try{const updated=await communityApi.update(editing.id,editing.caption);setPosts(items=>items.map(p=>p.id===updated.id?updated:p));setEditing(null);toast.success("Caption updated")}catch(error){toast.error(error.response?.data?.message||"Could not update post")}}
  async function remove(post){if(!window.confirm("Delete this post permanently?"))return;try{await communityApi.remove(post.id);setPosts(items=>items.filter(p=>p.id!==post.id));toast.success("Post deleted")}catch(error){toast.error(error.response?.data?.message||"Could not delete post")}}
  async function downloadImage(post){
    if(downloading.has(post.id))return;
    setDownloading(current=>new Set(current).add(post.id));
    try{const response=await fetch(post.mediaUrl);if(!response.ok)throw new Error();const blob=await response.blob();const extension=blob.type.split("/")[1]?.replace("jpeg","jpg")||"jpg";const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`networkers-story-${post.id}.${extension}`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);toast.success("Image downloaded")}catch{window.open(post.mediaUrl,"_blank","noopener,noreferrer");toast("Image opened in a new tab—save it from there.")}finally{setDownloading(current=>{const next=new Set(current);next.delete(post.id);return next})}
  }
  return <div className="mx-auto w-full space-y-5 md:w-[68%]"><header><p className="page-kicker">Member stories</p><h1 className="mt-1 page-title">Community <span className="text-brand-accent">Stories</span></h1><p className="mt-2 text-sm text-brand-muted">Photos and moments shared by members across every chapter.</p></header>
    {!loading&&visiblePosts.length===0&&<EmptyState title={yourPosts?"You have not posted yet":"No community stories yet"} message={yourPosts?"Create your first story and it will appear here.":"Be the first member to share a photo or update."}/>}
    {visiblePosts.map(post=><article className="overflow-hidden rounded-3xl border border-brand-border/15 bg-brand-panel shadow-premium" key={post.id}><header className="flex items-center gap-3 p-4"><Avatar member={post.author}/><div className="min-w-0 flex-1"><p className="font-bold">{post.author.name}</p><p className="text-xs text-brand-muted">{post.author.businessName||"Member"} · {post.chapterName||"Networkers"}</p></div>{String(post.author.id)===String(user?.id)&&<div className="flex gap-1"><button aria-label="Edit caption" className="glass-icon" onClick={()=>setEditing({id:post.id,caption:post.caption})}><Pencil size={16}/></button><button aria-label="Delete post" className="glass-icon !text-red-500" onClick={()=>remove(post)}><Trash2 size={16}/></button></div>}</header>
      {post.mediaUrl&&(post.mediaType==="VIDEO"?<video className="max-h-[680px] w-full bg-black object-contain" src={post.mediaUrl} controls preload="metadata"/>:<div className="relative"><img className="max-h-[680px] w-full bg-black object-contain" src={post.mediaUrl} alt={post.caption}/><button type="button" disabled={downloading.has(post.id)} onClick={()=>downloadImage(post)} className="absolute bottom-3 right-3 inline-flex items-center gap-2 rounded-xl bg-black/75 px-3 py-2 text-sm font-bold text-white shadow-lg backdrop-blur transition hover:bg-black" aria-label="Download story image"><Download size={17}/>{downloading.has(post.id)?"Downloading…":"Download"}</button></div>) }<div className="p-4"><div className="flex items-center gap-3"><button disabled={kudosPending.has(post.id)} onClick={()=>kudos(post.id)} className={`flex items-center gap-2 font-bold transition active:scale-95 ${post.kudosGiven?"text-red-500":"text-brand-muted"}`}><Heart size={23} fill={post.kudosGiven?"currentColor":"none"}/>Kudos</button>{post.kudosCount>0&&<button type="button" onClick={()=>setLikers({postId:post.id,members:post.kudosMembers||[]})} className="text-sm font-semibold text-brand-muted underline-offset-4 hover:text-brand-accent hover:underline">{post.kudosCount} {post.kudosCount===1?"person":"people"}</button>}</div><p className="mt-3 leading-7"><span className="mr-2 font-bold">{post.author.name}</span>{post.caption}</p>{post.mentions?.length>0&&<p className="mt-2 flex items-center gap-2 text-sm text-brand-accent"><Users size={15}/>With {post.mentions.map(m=>m.name).join(", ")}</p>}
      <div className="mt-4 space-y-2">{post.comments?.map(c=><p className="text-sm" key={c.id}><span className="mr-2 font-bold">{c.author.name}</span><span className="text-brand-muted">{c.content}</span></p>)}</div><form onSubmit={e=>comment(e,post.id)} className="mt-4 flex gap-2 border-t border-brand-border/15 pt-4"><MessageCircle className="mt-3 text-brand-muted" size={18}/><input className="field" placeholder="Add a comment..." value={comments[post.id]||""} onChange={e=>setComments({...comments,[post.id]:e.target.value})}/><button className="btn-primary">Post</button></form></div></article>)}
    <div className="fixed bottom-6 right-4 z-30 flex flex-col items-end gap-2 sm:right-6">
      <button type="button" aria-label="Scroll to top" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="glass-icon shadow-xl"><ArrowUp size={19}/></button>
      <button type="button" className={`your-posts-toggle flex h-14 w-40 items-center justify-center gap-2 rounded-full border font-bold shadow-xl transition hover:scale-105 ${yourPosts?"is-active border-red-500 bg-white text-red-600":"border-white/15 bg-[#252525] text-white"}`} onClick={()=>setYourPosts(v=>!v)}><Users size={18}/>{yourPosts?"All Posts":"Your Posts"}</button>
      <button type="button" onClick={()=>setComposerOpen(true)} className="flex h-14 w-40 items-center justify-center gap-2 rounded-full border border-red-400/50 bg-gradient-to-br from-[#ff1e1e] to-[#8b0000] font-bold text-white shadow-[0_0_35px_rgba(225,6,0,.45)] transition hover:scale-105"><Plus size={19}/>Create Post</button>
    </div>
    {composerOpen&&<Modal onClose={()=>!meetingId&&setComposerOpen(false)}><form onSubmit={publish}><div className="flex items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 text-xl font-bold"><ImagePlus className="text-brand-accent"/>{meetingId?"Required meeting post":"Create Post"}</h2><p className="mt-1 text-sm text-brand-muted">{meetingId?"Add a photo or video from your completed meeting.":"Share a photo, video, or update with the community."}</p></div>{!meetingId&&<button type="button" className="glass-icon" onClick={()=>setComposerOpen(false)}><X size={18}/></button>}</div><textarea required className="field mt-5" rows="4" placeholder="Write a caption..." value={composer.caption} onChange={e=>setComposer({...composer,caption:e.target.value})}/><input required={Boolean(meetingId)} className="field mt-3" type="file" accept="image/*,video/*" onChange={e=>setComposer({...composer,file:e.target.files?.[0]||null})}/><button disabled={publishing} className="btn-primary mt-4 w-full justify-center">{publishing?"Publishing...":"Publish Post"}</button></form></Modal>}
    {editing&&<Modal onClose={()=>setEditing(null)}><form onSubmit={saveEdit}><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Edit caption</h2><button type="button" className="glass-icon" onClick={()=>setEditing(null)}><X size={18}/></button></div><textarea autoFocus required className="field mt-5" rows="4" value={editing.caption} onChange={e=>setEditing({...editing,caption:e.target.value})}/><button className="btn-primary mt-4 w-full justify-center">Save Changes</button></form></Modal>}
    {likers&&<Modal onClose={()=>setLikers(null)}><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Kudos from</h2><p className="mt-1 text-sm text-brand-muted">Members who liked this story</p></div><button type="button" className="glass-icon" onClick={()=>setLikers(null)}><X size={18}/></button></div><div className="mt-5 max-h-96 space-y-3 overflow-y-auto">{likers.members.map(member=><div key={member.id} className="flex items-center gap-3 rounded-2xl border border-brand-border/15 p-3"><Avatar member={member}/><div><p className="font-bold">{member.name}</p>{member.businessName&&<p className="text-sm text-brand-muted">{member.businessName}</p>}</div></div>)}</div></Modal>}
  </div>
}
function Modal({children,onClose}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.()}}><div className="w-full max-w-xl rounded-3xl border border-brand-border/20 bg-brand-panel p-6 shadow-2xl">{children}</div></div>}
function Avatar({member}){return <div className="h-11 w-11 overflow-hidden rounded-full bg-brand-base">{member.avatar?<img className="h-full w-full object-cover" src={member.avatar} alt={member.name}/>:<span className="grid h-full place-items-center font-bold text-brand-accent">{member.name?.[0]}</span>}</div>}
