import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { Heart, ImagePlus, MessageCircle, Pencil, Plus, Trash2, Users, X } from "lucide-react";
import { communityApi } from "../../api/communityApi";
import { useAuth } from "../../context/AuthContext.jsx";
import EmptyState from "../../components/EmptyState.jsx";

export default function CommunityFeed(){
  const {user}=useAuth();
  const[params,setParams]=useSearchParams();const meetingId=params.get("meetingId");
  const[posts,setPosts]=useState([]);const[comments,setComments]=useState({});const[loading,setLoading]=useState(true);
  const[composer,setComposer]=useState({caption:"",file:null});const[publishing,setPublishing]=useState(false);const[composerOpen,setComposerOpen]=useState(Boolean(meetingId));
  const[yourPosts,setYourPosts]=useState(false);const[editing,setEditing]=useState(null);const[kudosPending,setKudosPending]=useState(new Set());
  const load=()=>communityApi.all().then(v=>setPosts(Array.isArray(v)?v:[])).catch(()=>setPosts([])).finally(()=>setLoading(false));
  useEffect(()=>{load()},[]);useEffect(()=>{if(meetingId)setComposerOpen(true)},[meetingId]);
  const visiblePosts=useMemo(()=>yourPosts?posts.filter(p=>String(p.author.id)===String(user?.id)):posts,[posts,yourPosts,user?.id]);
  async function kudos(id){
    if(kudosPending.has(id))return;
    const previous=posts.find(p=>p.id===id);if(!previous)return;
    setKudosPending(s=>new Set(s).add(id));
    setPosts(items=>items.map(p=>p.id===id?{...p,kudosGiven:!p.kudosGiven,kudosCount:Math.max(0,p.kudosCount+(p.kudosGiven?-1:1))}:p));
    try{const updated=await communityApi.kudos(id);setPosts(items=>items.map(p=>p.id===id?updated:p))}catch(e){setPosts(items=>items.map(p=>p.id===id?previous:p));toast.error(e.response?.data?.message||"Could not update kudos")}finally{setKudosPending(s=>{const n=new Set(s);n.delete(id);return n})}
  }
  async function comment(e,id){e.preventDefault();const value=comments[id]?.trim();if(!value)return;try{const added=await communityApi.comment(id,value);setComments(v=>({...v,[id]:""}));setPosts(items=>items.map(p=>p.id===id?{...p,comments:[...(p.comments||[]),added]}:p))}catch(error){toast.error(error.response?.data?.message||"Could not comment")}}
  async function publish(e){e.preventDefault();if(meetingId&&!composer.file)return toast.error("A completed meeting post requires a photo or video");const body=new FormData();body.append("caption",composer.caption);if(meetingId)body.append("meetingId",meetingId);if(composer.file)body.append("file",composer.file);setPublishing(true);try{const created=await communityApi.create(body);setPosts(items=>[created,...items]);setComposer({caption:"",file:null});setParams({});setComposerOpen(false);toast.success(meetingId?"Meeting completion post published":"Post published")}catch(error){toast.error(error.response?.data?.message||"Could not publish post")}finally{setPublishing(false)}}
  async function saveEdit(e){e.preventDefault();try{const updated=await communityApi.update(editing.id,editing.caption);setPosts(items=>items.map(p=>p.id===updated.id?updated:p));setEditing(null);toast.success("Caption updated")}catch(error){toast.error(error.response?.data?.message||"Could not update post")}}
  async function remove(post){if(!window.confirm("Delete this post permanently?"))return;try{await communityApi.remove(post.id);setPosts(items=>items.filter(p=>p.id!==post.id));toast.success("Post deleted")}catch(error){toast.error(error.response?.data?.message||"Could not delete post")}}
  return <div className="mx-auto w-full space-y-5 md:w-[68%]"><header className="flex items-end justify-between gap-4"><div><p className="page-kicker">Member stories</p><h1 className="mt-1 page-title">Community <span className="text-brand-accent">Stories</span></h1><p className="mt-2 text-sm text-brand-muted">Photos and moments shared by members across every chapter.</p></div><button className={`btn-muted shrink-0 ${yourPosts?"!border-red-500 !text-red-500":""}`} onClick={()=>setYourPosts(v=>!v)}>{yourPosts?"All Posts":"Your Posts"}</button></header>
    {!loading&&visiblePosts.length===0&&<EmptyState title={yourPosts?"You have not posted yet":"No community stories yet"} message={yourPosts?"Create your first story and it will appear here.":"Be the first member to share a photo or update."}/>}
    {visiblePosts.map(post=><article className="overflow-hidden rounded-3xl border border-brand-border/15 bg-brand-panel shadow-premium" key={post.id}><header className="flex items-center gap-3 p-4"><Avatar member={post.author}/><div className="min-w-0 flex-1"><p className="font-bold">{post.author.name}</p><p className="text-xs text-brand-muted">{post.author.businessName||"Member"} · {post.chapterName||"Networkers"}</p></div>{String(post.author.id)===String(user?.id)&&<div className="flex gap-1"><button aria-label="Edit caption" className="glass-icon" onClick={()=>setEditing({id:post.id,caption:post.caption})}><Pencil size={16}/></button><button aria-label="Delete post" className="glass-icon !text-red-500" onClick={()=>remove(post)}><Trash2 size={16}/></button></div>}</header>
      {post.mediaUrl&&(post.mediaType==="VIDEO"?<video className="max-h-[680px] w-full bg-black object-contain" src={post.mediaUrl} controls preload="metadata"/>:<img className="max-h-[680px] w-full bg-black object-contain" src={post.mediaUrl} alt={post.caption}/>) }<div className="p-4"><button disabled={kudosPending.has(post.id)} onClick={()=>kudos(post.id)} className={`flex items-center gap-2 font-bold transition active:scale-95 ${post.kudosGiven?"text-red-500":"text-brand-muted"}`}><Heart size={23} fill={post.kudosGiven?"currentColor":"none"}/>{post.kudosCount} kudos</button><p className="mt-3 leading-7"><span className="mr-2 font-bold">{post.author.name}</span>{post.caption}</p>{post.mentions?.length>0&&<p className="mt-2 flex items-center gap-2 text-sm text-brand-accent"><Users size={15}/>With {post.mentions.map(m=>m.name).join(", ")}</p>}
      <div className="mt-4 space-y-2">{post.comments?.map(c=><p className="text-sm" key={c.id}><span className="mr-2 font-bold">{c.author.name}</span><span className="text-brand-muted">{c.content}</span></p>)}</div><form onSubmit={e=>comment(e,post.id)} className="mt-4 flex gap-2 border-t border-brand-border/15 pt-4"><MessageCircle className="mt-3 text-brand-muted" size={18}/><input className="field" placeholder="Add a comment..." value={comments[post.id]||""} onChange={e=>setComments({...comments,[post.id]:e.target.value})}/><button className="btn-primary">Post</button></form></div></article>)}
    <button onClick={()=>setComposerOpen(true)} className="fixed bottom-6 right-6 z-30 flex h-14 items-center gap-2 rounded-full border border-red-400/50 bg-gradient-to-br from-[#ff1e1e] to-[#8b0000] px-5 font-bold text-white shadow-[0_0_35px_rgba(225,6,0,.45)] transition hover:scale-105"><Plus/> <span className="hidden sm:inline">Create Post</span></button>
    {composerOpen&&<Modal onClose={()=>!meetingId&&setComposerOpen(false)}><form onSubmit={publish}><div className="flex items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 text-xl font-bold"><ImagePlus className="text-brand-accent"/>{meetingId?"Required meeting post":"Create Post"}</h2><p className="mt-1 text-sm text-brand-muted">{meetingId?"Add a photo or video from your completed meeting.":"Share a photo, video, or update with the community."}</p></div>{!meetingId&&<button type="button" className="glass-icon" onClick={()=>setComposerOpen(false)}><X size={18}/></button>}</div><textarea required className="field mt-5" rows="4" placeholder="Write a caption..." value={composer.caption} onChange={e=>setComposer({...composer,caption:e.target.value})}/><input required={Boolean(meetingId)} className="field mt-3" type="file" accept="image/*,video/*" onChange={e=>setComposer({...composer,file:e.target.files?.[0]||null})}/><button disabled={publishing} className="btn-primary mt-4 w-full justify-center">{publishing?"Publishing...":"Publish Post"}</button></form></Modal>}
    {editing&&<Modal onClose={()=>setEditing(null)}><form onSubmit={saveEdit}><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Edit caption</h2><button type="button" className="glass-icon" onClick={()=>setEditing(null)}><X size={18}/></button></div><textarea autoFocus required className="field mt-5" rows="4" value={editing.caption} onChange={e=>setEditing({...editing,caption:e.target.value})}/><button className="btn-primary mt-4 w-full justify-center">Save Changes</button></form></Modal>}
  </div>
}
function Modal({children,onClose}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.()}}><div className="w-full max-w-xl rounded-3xl border border-brand-border/20 bg-brand-panel p-6 shadow-2xl">{children}</div></div>}
function Avatar({member}){return <div className="h-11 w-11 overflow-hidden rounded-full bg-brand-base">{member.avatar?<img className="h-full w-full object-cover" src={member.avatar} alt={member.name}/>:<span className="grid h-full place-items-center font-bold text-brand-accent">{member.name?.[0]}</span>}</div>}
