import {useEffect,useState} from "react";
import {BarChart3,IndianRupee,Medal,Trophy,Users} from "lucide-react";
import {publicDashboardApi} from "../../api/publicDashboardApi.js";

export default function PublicDashboard(){
 const[data,setData]=useState(null),[page,setPage]=useState(0),[error,setError]=useState("");
 useEffect(()=>{const load=()=>publicDashboardApi.get(page).then(v=>{setData(v);setError("")}).catch(()=>setError("Dashboard data could not be loaded. Please refresh once the backend is running."));load();const timer=window.setInterval(load,10000);return()=>window.clearInterval(timer)},[page]);
 const trend=data?.revenueTrend||[],pages=data?Math.max(data.topReferrers.totalPages,data.mostActive.totalPages,data.topRevenueContributors.totalPages):0;
 return <div className="page-shell"><header><p className="page-kicker">Network leaderboard</p><h2 className="mt-1 page-title">Community <span className="text-brand-accent">Dashboard</span></h2><p className="mt-2 text-sm text-brand-muted">Historical results plus new activity, refreshed automatically.</p></header>
  {error&&<div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
  <section className="grid gap-4 md:grid-cols-[1fr_2fr]"><div className="glass-card rounded-3xl p-6"><IndianRupee className="text-red-500"/><p className="mt-6 text-sm font-bold uppercase tracking-wider text-brand-muted">Total revenue earned through Networkers referrals</p><p className="mt-2 text-4xl font-black">Rs {Number(data?.totalRevenue||0).toLocaleString("en-IN")}</p></div><RevenueChart points={trend}/></section>
  <section className="grid gap-5 xl:grid-cols-3"><RankTable icon={Trophy} title="Top Referrers" subtitle="Referrals shared" page={data?.topReferrers}/><RankTable icon={Users} title="Most Active" subtitle="Activity points" page={data?.mostActive}/><RankTable icon={BarChart3} title="Revenue Leaders" subtitle="Confirmed referral revenue" page={data?.topRevenueContributors} money/></section>
  {pages>1&&<div className="flex items-center justify-center gap-3"><button disabled={page===0} className="btn-muted" onClick={()=>setPage(p=>p-1)}>Previous</button><span className="text-sm text-brand-muted">Page {page+1} of {pages}</span><button disabled={page+1>=pages} className="btn-primary" onClick={()=>setPage(p=>p+1)}>Next</button></div>}
 </div>
}
function RankBadge({rank}){const style=rank===1?"border-yellow-300/60 text-yellow-300":rank===2?"border-slate-300/60 text-slate-200":rank===3?"border-amber-600/60 text-amber-500":"border-red-500/20 text-red-400";return <span title={rank===1?"Gold medal":rank===2?"Silver medal":rank===3?"Bronze medal":`Rank ${rank}`} className={`flex h-8 min-w-10 shrink-0 items-center justify-center gap-1 rounded-full border px-2 text-xs font-black ${style}`}><span>#{rank}</span>{rank<=3&&<Medal size={13}/>}</span>}
function rowHighlight(rank){return rank===1?"bg-yellow-400/[.07] ring-1 ring-inset ring-yellow-300/20":rank===2?"bg-slate-200/[.055] ring-1 ring-inset ring-slate-200/15":rank===3?"bg-amber-700/[.07] ring-1 ring-inset ring-amber-500/20":""}
function RankTable({icon:Icon,title,subtitle,page,money=false}){return <section className="overflow-hidden rounded-3xl border border-brand-border/15 bg-brand-panel"><div className="flex items-center gap-3 border-b border-brand-border/15 p-5"><Icon className="text-red-500"/><div><h3 className="font-bold">{title}</h3><p className="text-xs text-brand-muted">{subtitle}</p></div></div><div>{page?.content?.map((r,i)=>{const rank=page.page*page.size+i+1;return <div key={r.userId} className={`flex items-center gap-3 border-b border-brand-border/10 p-4 transition-colors last:border-0 ${rowHighlight(rank)}`}><RankBadge rank={rank}/><div className="h-10 w-10 shrink-0 overflow-hidden rounded-full bg-red-500/10">{r.avatar?<img className="h-full w-full object-cover" src={r.avatar} alt={r.name}/>:<span className="grid h-full place-items-center font-bold text-red-400">{r.name?.[0]}</span>}</div><div className="min-w-0 flex-1"><p className="truncate font-bold">{r.name}</p><p className="truncate text-xs text-brand-muted">{r.businessName||r.chapterName||"Member"}</p></div><strong className="shrink-0">{money?`Rs ${Number(r.score).toLocaleString("en-IN")}`:r.score}</strong></div>})}{page&&page.content.length===0&&<p className="p-6 text-center text-sm text-brand-muted">No ranking data yet.</p>}</div></section>}
function RevenueChart({points}){const values=points.map(p=>Number(p.value)),max=Math.max(...values,1),coords=values.map((v,i)=>`${points.length===1?50:i/(points.length-1)*100},${92-v/max*75}`).join(" ");return <section className="glass-card rounded-3xl p-6"><div><h3 className="font-bold">Network Revenue Growth</h3><p className="text-xs text-brand-muted">Confirmed referral revenue earned by members each month</p></div><div className="mt-5 h-48"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full overflow-visible" aria-label="Network revenue area graph"><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff1e1e" stopOpacity=".5"/><stop offset="1" stopColor="#8b0000" stopOpacity=".04"/></linearGradient></defs>{points.length>0&&<><polygon points={`0,100 ${coords} 100,100`} fill="url(#revenueFill)"/><polyline points={coords} fill="none" stroke="#ff1e1e" strokeWidth="2" vectorEffect="non-scaling-stroke"/></>}</svg></div><div className="mt-2 flex justify-between text-[10px] text-brand-muted"><span>{points[0]?.label||"No confirmed revenue yet"}</span><span>{points.at(-1)?.label||""}</span></div></section>}
