import {useEffect,useMemo,useState} from "react";
import {BarChart3,CalendarCheck,IndianRupee,Medal,Trophy,Users} from "lucide-react";
import {motion} from "framer-motion";
import {publicDashboardApi} from "../../api/publicDashboardApi.js";

const months=Array.from({length:12},(_,i)=>({value:i+1,label:new Intl.DateTimeFormat("en",{month:"long"}).format(new Date(2024,i,1))}));

export default function PublicDashboard(){
 const now=new Date(),[data,setData]=useState(null),[page,setPage]=useState(0),[month,setMonth]=useState(now.getMonth()+1),[year,setYear]=useState(now.getFullYear()),[error,setError]=useState("");
 const years=useMemo(()=>Array.from({length:6},(_,i)=>now.getFullYear()-i),[]);
 useEffect(()=>{const load=()=>publicDashboardApi.get(page,month,year).then(v=>{setData(v);setError("")}).catch(()=>setError("Dashboard data could not be loaded. Please refresh once the backend is running."));load();const timer=window.setInterval(load,10000);return()=>window.clearInterval(timer)},[page,month,year]);
 const trend=data?.revenueTrend||[],boards=[data?.topReferrers,data?.mostActive,data?.topRevenueContributors,data?.topAttenders],pages=data?Math.max(...boards.map(v=>v?.totalPages||0)):0;
 const changeFilter=setter=>e=>{setter(Number(e.target.value));setPage(0)};
 return <div className="page-shell"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="page-kicker">Network leaderboard</p><h2 className="mt-1 page-title">Community <span className="text-brand-accent">Dashboard</span></h2><p className="mt-2 text-sm text-brand-muted">Monthly community performance, refreshed automatically.</p></div></header>
  {error&&<div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
  <section className="grid gap-4 md:grid-cols-[1fr_2fr]"><div className="glass-card rounded-3xl p-6"><div className="flex flex-wrap gap-2" aria-label="Revenue period"><select className="field !w-auto !py-2" value={month} onChange={changeFilter(setMonth)} aria-label="Revenue month">{months.map(m=><option key={m.value} value={m.value}>{m.label}</option>)}</select><select className="field !w-auto !py-2" value={year} onChange={changeFilter(setYear)} aria-label="Revenue year">{years.map(y=><option key={y}>{y}</option>)}</select></div><IndianRupee className="mt-6 text-red-500"/><p className="mt-3 text-sm font-bold uppercase tracking-wider text-brand-muted">Revenue generated in {months[month-1].label} {year}</p><p className="mt-2 text-4xl font-black">Rs {Number(data?.selectedRevenue||0).toLocaleString("en-IN")}</p><p className="mt-4 text-sm text-brand-muted"><strong className="text-brand-text">{data?.selectedReferralCount||0}</strong> referrals given this month</p></div><RevenueChart points={trend}/></section>
  <section className="grid gap-5 xl:grid-cols-2"><RankTable icon={Trophy} title="Top Referrers" subtitle={`${months[month-1].label} ${year} · referrals shared`} page={data?.topReferrers}/><RankTable icon={Users} title="Most Active" subtitle={`${months[month-1].label} ${year} · activity points`} page={data?.mostActive}/><RankTable icon={BarChart3} title="Revenue Leaders" subtitle={`${months[month-1].label} ${year} · confirmed revenue`} page={data?.topRevenueContributors} money/><RankTable icon={CalendarCheck} title="Top Attenders" subtitle={`${months[month-1].label} ${year} · events attended`} page={data?.topAttenders}/></section>
  {pages>1&&<div className="flex items-center justify-center gap-3"><button disabled={page===0} className="btn-muted" onClick={()=>setPage(p=>p-1)}>Previous</button><span className="text-sm text-brand-muted">Page {page+1} of {pages}</span><button disabled={page+1>=pages} className="btn-primary" onClick={()=>setPage(p=>p+1)}>Next</button></div>}
 </div>
}
function RankBadge({rank}){const style=rank===1?"border-yellow-300/60 text-yellow-300":rank===2?"border-slate-300/60 text-slate-200":rank===3?"border-amber-600/60 text-amber-500":"border-red-500/20 text-red-400";return <span className={`flex h-8 min-w-10 shrink-0 items-center justify-center gap-1 rounded-full border px-2 text-xs font-black ${style}`}><span>#{rank}</span>{rank<=3&&<Medal size={13}/>}</span>}
function rowHighlight(rank){return rank===1?"bg-yellow-400/[.07] ring-1 ring-inset ring-yellow-300/20":rank===2?"bg-slate-200/[.055] ring-1 ring-inset ring-slate-200/15":rank===3?"bg-amber-700/[.07] ring-1 ring-inset ring-amber-500/20":""}
function RankTable({icon:Icon,title,subtitle,page,money=false}){return <section className="overflow-hidden rounded-3xl border border-brand-border/15 bg-brand-panel"><div className="flex items-center gap-3 border-b border-brand-border/15 p-5"><Icon className="text-red-500"/><div><h3 className="font-bold">{title}</h3><p className="text-xs text-brand-muted">{subtitle}</p></div></div><div>{page?.content?.map((r,i)=>{const rank=page.page*page.size+i+1;return <div key={r.userId} className={`flex items-center gap-3 border-b border-brand-border/10 p-4 transition-colors last:border-0 ${rowHighlight(rank)}`}><RankBadge rank={rank}/><div className="h-10 w-10 shrink-0 overflow-hidden rounded-full bg-red-500/10">{r.avatar?<img className="h-full w-full object-cover" src={r.avatar} alt={r.name}/>:<span className="grid h-full place-items-center font-bold text-red-400">{r.name?.[0]}</span>}</div><div className="min-w-0 flex-1"><p className="truncate font-bold">{r.name}</p><p className="truncate text-xs text-brand-muted">{r.businessName||r.chapterName||"Member"}</p></div><strong className="shrink-0">{money?`Rs ${Number(r.score).toLocaleString("en-IN")}`:r.score}</strong></div>})}{page&&page.content.length===0&&<p className="p-6 text-center text-sm text-brand-muted">No ranking data for this period.</p>}</div></section>}
function RevenueChart({points}){const values=points.map(p=>Number(p.value)),max=Math.max(...values,1),coords=values.map((v,i)=>`${points.length===1?50:i/(points.length-1)*100},${92-v/max*75}`).join(" ");return <section className="glass-card rounded-3xl p-6"><div><h3 className="font-bold">Network Revenue Growth</h3><p className="text-xs text-brand-muted">Confirmed referral revenue earned by members each month</p></div><div className="mt-5 h-48"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full overflow-visible" aria-label="Network revenue area graph"><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff1e1e" stopOpacity=".5"/><stop offset="1" stopColor="#8b0000" stopOpacity=".04"/></linearGradient></defs>{points.length>0&&<><motion.polygon key={`area-${coords}`} points={`0,100 ${coords} 100,100`} fill="url(#revenueFill)" initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.8}}/><motion.polyline key={coords} points={coords} fill="none" stroke="#ff1e1e" strokeWidth="2" vectorEffect="non-scaling-stroke" initial={{pathLength:0,opacity:0}} animate={{pathLength:1,opacity:1}} transition={{duration:1.25,ease:"easeOut"}}/></>}</svg></div><div className="mt-2 flex justify-between text-[10px] text-brand-muted"><span>{points[0]?.label||"No confirmed revenue yet"}</span><span>{points.at(-1)?.label||""}</span></div></section>}
