import {useEffect,useState} from "react";
import {useNavigate} from "react-router-dom";
import toast from "react-hot-toast";
import {CalendarDays,CheckCircle2,Clock3,Crown,ImagePlus,MessageCircle,Users} from "lucide-react";
import {monthlyMeetingApi} from "../../api/meetingApi";
import EmptyState from "../../components/EmptyState.jsx";
import {useAuth} from "../../context/AuthContext.jsx";

function localToday(){const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10)}

export default function MyMeetings(){
  const{user}=useAuth();const navigate=useNavigate();const[month,setMonth]=useState(new Date().toISOString().slice(0,7));const[monthly,setMonthly]=useState(null);const[error,setError]=useState("");const[edit,setEdit]=useState(null);const[pairForm,setPairForm]=useState(null);const[completing,setCompleting]=useState(false);const[comment,setComment]=useState("");
  const load=()=>monthlyMeetingApi.mine(month).then(v=>{setMonthly(v);setError("")}).catch(e=>{setMonthly(null);setError(e.response?.data?.message||"No monthly group has been generated yet.")});
  useEffect(()=>{load()},[month]);
  async function save(e){e.preventDefault();const today=localToday();if(edit.date<today||edit.endDate<today)return toast.error("Meeting dates cannot be in the past");if(edit.endDate<edit.date)return toast.error("End date cannot be before start date");try{await monthlyMeetingApi.edit(monthly.id,edit);setEdit(null);toast.success("Meeting window updated");load()}catch(e){toast.error(e.response?.data?.message||"Could not update meeting window")}}
  async function completePair(e){e.preventDefault();if(completing)return;setCompleting(true);const body=new FormData();body.append("metOn",pairForm.metOn);body.append("notes",pairForm.notes);if(pairForm.photo)body.append("photo",pairForm.photo);try{await monthlyMeetingApi.completePair(monthly.id,pairForm.id,body);setPairForm(null);toast.success("One-to-one meeting completed");await load()}catch(e){toast.error(e.response?.data?.message||"Could not complete meeting")}finally{setCompleting(false)}}
  async function postComment(e){e.preventDefault();if(!comment.trim())return;try{await monthlyMeetingApi.comment(monthly.id,comment);setComment("");load()}catch(e){toast.error(e.response?.data?.message||"Could not comment")}}
  async function submitOutcome(){try{const updated=await monthlyMeetingApi.edit(monthly.id,{status:"COMPLETED"});toast.success(`Final progress: ${updated.completionPercentage}%`);navigate(`/community?meetingId=${monthly.id}&completion=${updated.completionPercentage}`)}catch(e){toast.error(e.response?.data?.message||"The final report is not available yet")}}
  const isHost=monthly?.host.id===user?.id;const today=localToday();const canReport=isHost&&monthly&&(today>monthly.endDate||monthly.completionPercentage===100)&&!["COMPLETED","INCOMPLETE"].includes(monthly.status);
  return <div className="space-y-6"><header><p className="page-kicker">Monthly one-to-one networking</p><h1 className="mt-1 page-title">Your Monthly <span className="text-brand-accent">Meetings</span></h1><p className="mt-2 text-sm text-brand-muted">Meet every other member in your group individually and record each meeting.</p><input aria-label="Meeting month" className="field mt-4 max-w-[210px]" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></header>
    {!monthly?<EmptyState title="Monthly meeting unavailable" message={error}/>:<section className="glass-card rounded-3xl p-5 md:p-7">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><span className="status-pill">Group {monthly.groupNumber}</span><h2 className="mt-4 flex items-center gap-2 text-2xl font-bold"><Crown className="text-brand-accent" size={21}/>{monthly.host.name}</h2><p className="text-sm text-brand-muted">Host · {monthly.chapterName}</p></div><span className="status-pill">{monthly.status}</span></div>
      <div className="mt-6 grid gap-3 md:grid-cols-3"><Info icon={CalendarDays} label="Meeting window" value={`${monthly.date} to ${monthly.endDate}`}/><Info icon={Users} label="Group" value={`${monthly.members.length} members · ${monthly.totalPairs} pairs`}/><Info icon={Clock3} label="Progress" value={`${monthly.completedPairs}/${monthly.totalPairs} · ${monthly.completionPercentage}%`}/></div>
      <div className="mt-4 h-3 overflow-hidden rounded-full bg-brand-panel"><div className="h-full rounded-full bg-brand-accent transition-all" style={{width:`${monthly.completionPercentage}%`}}/></div>
      {isHost&&monthly.editCount<monthly.maxEdits&&<button className="btn-primary mt-6" onClick={()=>setEdit({date:monthly.date,endDate:monthly.endDate,time:monthly.time,venue:monthly.venue||""})}>Set meeting window ({monthly.maxEdits-monthly.editCount} edits left)</button>}
      {edit&&<form onSubmit={save} className="mt-5 grid gap-3 rounded-2xl bg-brand-panel p-4 md:grid-cols-2"><label className="text-sm">Start date<input required min={today} className="field mt-1" type="date" value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value,endDate:edit.endDate<e.target.value?e.target.value:edit.endDate})}/></label><label className="text-sm">End date (maximum 10 days)<input required min={edit.date>today?edit.date:today} className="field mt-1" type="date" value={edit.endDate} onChange={e=>setEdit({...edit,endDate:e.target.value})}/></label><input className="field" type="time" value={edit.time} onChange={e=>setEdit({...edit,time:e.target.value})}/><input className="field" placeholder="Suggested venue / area (optional)" value={edit.venue} onChange={e=>setEdit({...edit,venue:e.target.value})}/><div className="flex gap-2"><button className="btn-primary">Save window</button><button type="button" className="btn-muted" onClick={()=>setEdit(null)}>Cancel</button></div></form>}
      <h3 className="mt-8 text-lg font-bold">{isHost?"Group one-to-one meetings":"Your one-to-one meetings"}</h3><div className="mt-4 grid gap-4 md:grid-cols-2">{monthly.pairMeetings.map(pair=>{const belongs=pair.memberOne.id===user?.id||pair.memberTwo.id===user?.id;const person=belongs?(pair.memberOne.id===user?.id?pair.memberTwo:pair.memberOne):null;const label=person?.name||`${pair.memberOne.name} + ${pair.memberTwo.name}`;return <article className={`rounded-2xl border p-4 ${pair.completed?"border-green-500/25 bg-green-500/5":"border-brand-border/20 bg-brand-panel"}`} key={pair.id}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Avatar member={person||pair.memberOne}/><div><p className="font-bold">{label}</p><p className="text-xs text-brand-muted">{pair.completed?`Met on ${pair.metOn}`:"Pending"}</p></div></div>{pair.completed?<CheckCircle2 className="text-green-400"/>:<Clock3 className="text-brand-accent"/>}</div>{pair.completed&&pair.photoUrl&&<img className="mt-3 h-36 w-full rounded-xl object-cover" src={pair.photoUrl} alt="One-to-one meeting"/>}{!pair.completed&&belongs&&today>=monthly.date&&today<=monthly.endDate&&<button className="btn-primary mt-4 w-full justify-center" onClick={()=>setPairForm({id:pair.id,name:label,metOn:today,notes:"",photo:null})}>Record completed meeting</button>}</article>})}</div>
      {pairForm&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm" onClick={()=>!completing&&setPairForm(null)}><form onSubmit={completePair} className="card w-full max-w-lg p-5 sm:p-6" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label={`Complete meeting with ${pairForm.name}`}><h3 className="text-xl font-bold">Meeting with {pairForm.name}</h3><p className="mt-1 text-sm text-brand-muted">Record the completed one-to-one meeting. A photo is optional.</p><label className="mt-4 block text-sm font-bold">Meeting date<input required min={monthly.date} max={today<monthly.endDate?today:monthly.endDate} className="field mt-1" type="date" value={pairForm.metOn} onChange={e=>setPairForm({...pairForm,metOn:e.target.value})}/></label><textarea className="field mt-3" rows="3" placeholder="What did you discuss? (optional)" value={pairForm.notes} onChange={e=>setPairForm({...pairForm,notes:e.target.value})}/><label className="mt-3 flex cursor-pointer items-center gap-2 rounded-xl border border-brand-border/20 p-3 text-sm"><ImagePlus size={18}/>Upload meeting photo (optional)<input className="hidden" type="file" accept="image/*" onChange={e=>setPairForm({...pairForm,photo:e.target.files?.[0]||null})}/>{pairForm.photo&&<span className="min-w-0 truncate text-brand-accent">{pairForm.photo.name}</span>}</label><div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" className="btn-muted" disabled={completing} onClick={()=>setPairForm(null)}>Cancel</button><button className="btn-primary" disabled={completing}>{completing&&<span className="spinner"/>}{completing?"Completing...":"Complete meeting"}</button></div></form></div>}
      {canReport&&<div className="mt-7 rounded-2xl border border-brand-accent/30 bg-brand-panel p-5"><h3 className="font-bold">Host final group report</h3><p className="mt-1 text-sm text-brand-muted">Current completion is {monthly.completionPercentage}%. Submit the final status, then upload the group update photo to the community feed.</p><button className="btn-primary mt-4" onClick={submitOutcome}>Submit {monthly.completionPercentage}% report and create post</button></div>}
      <div className="mt-8 border-t border-brand-border/20 pt-6"><h3 className="flex items-center gap-2 text-lg font-bold"><MessageCircle className="text-brand-accent" size={18}/>Group discussion</h3><div className="mt-4 space-y-3">{monthly.comments.map(c=><div className="rounded-2xl bg-brand-panel p-4" key={c.id}><p className="text-sm font-bold">{c.authorName}</p><p className="mt-1 text-sm text-brand-muted">{c.text}</p></div>)}</div><form onSubmit={postComment} className="mt-4 flex gap-2"><input className="field" placeholder="Comment for your group..." value={comment} onChange={e=>setComment(e.target.value)}/><button className="btn-primary">Post</button></form></div>
    </section>}
  </div>
}
function Info({icon:Icon,label,value}){return <div className="rounded-2xl border border-brand-border/15 bg-brand-panel p-4"><Icon className="text-brand-accent" size={18}/><p className="mt-3 text-xs uppercase tracking-wider text-brand-muted">{label}</p><p className="mt-1 font-bold">{value}</p></div>}
function Avatar({member}){return <div className="h-11 w-11 shrink-0 overflow-hidden rounded-full bg-brand-base">{member?.avatar?<img className="h-full w-full object-cover" src={member.avatar} alt={member.name}/>:<span className="grid h-full place-items-center font-bold text-brand-accent">{member?.name?.[0]||"?"}</span>}</div>}
