import { useEffect, useMemo, useState } from "react";
import toast from "react-hot-toast";
import { CalendarDays, CheckCircle2, Clock3, ImagePlus, Medal, MessageCircle, Users } from "lucide-react";
import { monthlyMeetingApi } from "../../api/meetingApi";
import EmptyState from "../../components/EmptyState.jsx";
import { useAuth } from "../../context/AuthContext.jsx";

function localToday(){const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10)}

export default function MyMeetings(){
  const{user}=useAuth();const[data,setData]=useState(null);const[error,setError]=useState("");const[pairForm,setPairForm]=useState(null);const[busy,setBusy]=useState(false);const[comment,setComment]=useState("");
  const load=()=>monthlyMeetingApi.cycleMine().then(value=>{setData(value);setError("")}).catch(e=>{setData(null);setError(e.response?.data?.message||"No face-to-face cycle has been started yet.")});useEffect(()=>{load()},[]);
  const meeting=data?.currentGroup;const today=localToday();const ownPairs=useMemo(()=>meeting?.pairMeetings.filter(pair=>pair.memberOne.id===user?.id||pair.memberTwo.id===user?.id)||[],[meeting,user?.id]);
  async function completePair(event){event.preventDefault();if(busy)return;if(!pairForm.notes.trim())return toast.error("Meeting description is required");if(!pairForm.photo)return toast.error("Meeting photo is required");setBusy(true);const body=new FormData();body.append("metOn",pairForm.metOn);body.append("notes",pairForm.notes.trim());body.append("photo",pairForm.photo);try{await monthlyMeetingApi.completePair(meeting.id,pairForm.id,body);setPairForm(null);toast.success("Meeting completed, point earned, and story posted");await load()}catch(e){toast.error(e.response?.data?.message||"Could not update meeting")}finally{setBusy(false)}}
  async function postComment(event){event.preventDefault();if(!comment.trim())return;try{await monthlyMeetingApi.comment(meeting.id,comment);setComment("");load()}catch(e){toast.error(e.response?.data?.message||"Could not comment")}}
  if(!data)return <div className="space-y-6"><PageHeader/><EmptyState title="Face-to-face cycle unavailable" message={error}/></div>;
  return <div className="space-y-6"><PageHeader/><section className="glass-card rounded-3xl p-5 md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="status-pill">Cycle {data.cycle.cycleNumber}</span><h2 className="mt-3 text-2xl font-bold">{data.cycle.chapterName}</h2><p className="mt-1 text-sm text-brand-muted">Started {data.cycle.startDate}{data.cycle.nextCycleDate&&` · Next cycle ${data.cycle.nextCycleDate}`}</p></div><span className="status-pill">{data.cycle.status}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Info icon={Users} label="Chapter meetings" value={`${data.progress.completedPairs}/${data.progress.totalPairs}`}/><Info icon={Medal} label="Cycle progress" value={`${data.progress.completionPercentage}%`}/><Info icon={Clock3} label="Your score" value={`${data.leaderboard.find(entry=>String(entry.member.id)===String(user?.id))?.points||0} points`}/></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-brand-panel"><div className="h-full rounded-full bg-brand-accent" style={{width:`${data.progress.completionPercentage}%`}}/></div></section>
    {!meeting?<EmptyState title="Waiting for the next group round" message="Your next group will be generated automatically after the five-day interval."/>:<><section className="glass-card rounded-3xl p-5 md:p-7"><div className="flex flex-wrap justify-between gap-3"><div><span className="status-pill">Group {meeting.groupNumber}</span><h2 className="mt-3 text-xl font-bold">Current 10-day meeting window</h2></div><span className="status-pill">{meeting.status}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Info icon={CalendarDays} label="Window" value={`${meeting.date} to ${meeting.endDate}`}/><Info icon={Clock3} label="Suggested time" value={meeting.time}/><Info icon={Users} label="Assigned meetings" value={`${meeting.completedPairs}/${meeting.totalPairs}`}/></div><div className="mt-4 flex flex-wrap gap-2">{meeting.members.map(member=><span className="rounded-full bg-brand-panel px-3 py-1 text-xs" key={member.id}>{member.name}</span>)}</div></section>
      <PairSection pairs={ownPairs} user={user} meeting={meeting} today={today} onUpdate={setPairForm}/>
      <section className="glass-card rounded-3xl p-5 md:p-7"><h3 className="flex items-center gap-2 text-lg font-bold"><MessageCircle className="text-brand-accent" size={18}/>Group discussion</h3><div className="mt-4 space-y-3">{meeting.comments.map(item=><div className="rounded-2xl bg-brand-panel p-4" key={item.id}><p className="text-sm font-bold">{item.authorName}</p><p className="mt-1 text-sm text-brand-muted">{item.text}</p></div>)}</div><form onSubmit={postComment} className="mt-4 flex gap-2"><input className="field" placeholder="Comment for your group..." value={comment} onChange={e=>setComment(e.target.value)}/><button className="btn-primary">Post</button></form></section></>}
    <Leaderboard items={data.leaderboard}/>
    {pairForm&&<Modal onClose={()=>!busy&&setPairForm(null)}><form onSubmit={completePair}><h3 className="text-xl font-bold">Meeting Update: {pairForm.name}</h3><p className="mt-1 text-sm text-brand-muted">A photo and description are required. They will automatically create a Community Story when the meeting is completed.</p><label className="mt-4 block text-sm font-bold">Meeting date<input required min={meeting.date} max={today<meeting.endDate?today:meeting.endDate} className="field mt-1" type="date" value={pairForm.metOn} onChange={e=>setPairForm({...pairForm,metOn:e.target.value})}/></label><label className="mt-3 block text-sm font-bold">Meeting description *<textarea required className="field mt-1" rows="4" placeholder="Describe the meeting and what you discussed..." value={pairForm.notes} onChange={e=>setPairForm({...pairForm,notes:e.target.value})}/></label><label className="mt-3 flex cursor-pointer items-center gap-2 rounded-xl border border-brand-border/20 p-3 text-sm font-bold"><ImagePlus size={18}/>Upload meeting photo *<input required className="hidden" type="file" accept="image/*" onChange={e=>setPairForm({...pairForm,photo:e.target.files?.[0]||null})}/>{pairForm.photo&&<span className="truncate text-brand-accent">{pairForm.photo.name}</span>}</label><div className="mt-5 flex justify-end gap-2"><button type="button" className="btn-muted" onClick={()=>setPairForm(null)}>Cancel</button><button className="btn-primary" disabled={busy}>{busy?"Completing and posting...":"Mark complete & post story"}</button></div></form></Modal>}
  </div>;
}
function PageHeader(){return <header><p className="page-kicker">Chapter-wide meeting cycle</p><h1 className="mt-1 page-title">Face to <span className="text-brand-accent">Face</span></h1><p className="mt-2 text-sm text-brand-muted">Meet every chapter member through convenient, automatically generated group rounds.</p></header>}
function PairSection({pairs,user,meeting,today,onUpdate}){return <section className="glass-card rounded-3xl p-5 md:p-7"><h2 className="text-xl font-bold">Your one-to-one meetings</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{pairs.map(pair=>{const person=pair.memberOne.id===user?.id?pair.memberTwo:pair.memberOne;return <article className={`rounded-2xl border p-4 ${pair.completed?"border-green-500/25 bg-green-500/5":"border-brand-border/20 bg-brand-panel"}`} key={pair.id}><div className="flex items-center justify-between"><div><p className="font-bold">{person.name}</p><p className="text-xs text-brand-muted">{pair.completed?`Completed on ${pair.metOn} · 1 point earned · Story posted`:"Pending"}</p></div>{pair.completed?<CheckCircle2 className="text-green-400"/>:<Clock3 className="text-brand-accent"/>}</div>{pair.photoUrl&&<img className="mt-3 h-36 w-full rounded-xl object-cover" src={pair.photoUrl} alt="One-to-one meeting"/>}<div className="mt-4 flex gap-2">{!pair.completed&&today>=meeting.date&&today<=meeting.endDate&&<button className="btn-primary flex-1 justify-center" onClick={()=>onUpdate({id:pair.id,name:person.name,metOn:today,notes:"",photo:null})}>Meeting Update</button>}</div></article>})}{pairs.length===0&&<p className="text-sm text-brand-muted">No assignments in this group.</p>}</div></section>}
function Leaderboard({items}){return <section className="glass-card rounded-3xl p-5 md:p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><Medal className="text-brand-accent"/>Current cycle leaderboard</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{items.map((entry,index)=><div className="flex items-center gap-3 rounded-2xl bg-brand-panel p-3" key={entry.member.id}><strong className="text-brand-accent">#{index+1}</strong><span className="min-w-0 flex-1 truncate font-bold">{entry.member.name}</span><span>{entry.points} pts</span></div>)}</div></section>}
function Modal({children,onClose}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="card max-h-[90vh] w-full max-w-xl overflow-y-auto p-5 sm:p-6">{children}</div></div>}
function Info({icon:Icon,label,value}){return <div className="rounded-2xl border border-brand-border/15 bg-brand-panel p-4"><Icon className="text-brand-accent" size={18}/><p className="mt-3 text-xs uppercase tracking-wider text-brand-muted">{label}</p><p className="mt-1 font-bold">{value}</p></div>}
