package com.networkers.meetingautomation;
import com.networkers.chapter.*; import com.networkers.community.PostRepository; import com.networkers.notification.NotificationService; import com.networkers.user.*; import jakarta.persistence.EntityNotFoundException; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class MeetingAutomationService {
 private static final int MAX_GROUP_SIZE=10; private static final LocalTime DEFAULT_TIME=LocalTime.of(19,0);
 private final ChapterRepository chapters; private final UserRepository users; private final MeetingGroupRepository groups; private final MeetingParticipantRepository participants; private final MonthlyMeetingRepository meetings; private final MeetingCommentRepository comments; private final PostRepository posts; private final NotificationService notifications;
 public MeetingAutomationService(ChapterRepository c,UserRepository u,MeetingGroupRepository g,MeetingParticipantRepository p,MonthlyMeetingRepository m,MeetingCommentRepository x,PostRepository posts,NotificationService n){chapters=c;users=u;groups=g;participants=p;meetings=m;comments=x;this.posts=posts;notifications=n;}
 @Scheduled(cron="0 0 1 1 * *",zone="Asia/Kolkata") @Transactional public void monthly(){YearMonth ym=YearMonth.now(ZoneId.of("Asia/Kolkata"));for(Chapter c:chapters.findByActiveTrueOrderByChapterNumberAsc())if(!groups.existsByChapterIdAndYearAndMonth(c.getId(),ym.getYear(),ym.getMonthValue()))generate(c,ym);}
 @Scheduled(cron="0 0 9 * * *",zone="Asia/Kolkata") @Transactional public void reminders(){LocalDate tomorrow=LocalDate.now(ZoneId.of("Asia/Kolkata")).plusDays(1);for(MonthlyMeeting m:meetings.findByScheduledDateAndReminderSentFalse(tomorrow)){for(MeetingParticipant p:participants.findByGroupIdOrderByMemberFullNameAsc(m.getGroup().getId()))notifications.notify(p.getMember(),"Meeting tomorrow","Your Networkers Group "+m.getGroup().getGroupNumber()+" meeting is tomorrow at "+m.getScheduledTime()+". Venue: "+(m.getVenue()==null||m.getVenue().isBlank()?"not decided by host":m.getVenue())+".");m.setReminderSent(true);meetings.save(m);}}
 @Transactional public List<MeetingView> regenerate(Long chapterId,YearMonth ym){Chapter c=chapters.findById(chapterId).orElseThrow(()->new EntityNotFoundException("Chapter not found"));List<MeetingGroup> old=groups.findByChapterIdAndYearAndMonthOrderByGroupNumber(chapterId,ym.getYear(),ym.getMonthValue());for(MeetingGroup g:old){posts.unlinkMeetingGroup(g.getId());comments.deleteByMeetingGroupId(g.getId());meetings.deleteByGroupId(g.getId());participants.deleteByGroupId(g.getId());}groups.deletePeriod(chapterId,ym.getYear(),ym.getMonthValue());groups.flush();generate(c,ym);return overview(chapterId,ym);}
 private void generate(Chapter chapter,YearMonth ym){LocalDate today=LocalDate.now(ZoneId.of("Asia/Kolkata"));if(ym.isBefore(YearMonth.from(today)))throw new IllegalArgumentException("Meetings cannot be generated for a past month");LocalDate firstAvailable=ym.equals(YearMonth.from(today))?today.plusDays(1):ym.atDay(1);if(firstAvailable.isAfter(ym.atEndOfMonth()))throw new IllegalArgumentException("No future date is available in "+ym+". Select a future month.");List<User> members=new ArrayList<>(users.findByChapterAndEnabledTrueAndDeletedFalseOrderByFullNameAsc(chapter));if(members.isEmpty())return;Collections.shuffle(members);int count=Math.max(1,(int)Math.ceil((double)members.size()/MAX_GROUP_SIZE));List<List<User>> buckets=new ArrayList<>();for(int i=0;i<count;i++)buckets.add(new ArrayList<>());for(int i=0;i<members.size();i++)buckets.get(i%count).add(members.get(i));Random random=new Random();int availableDays=(int)(ym.atEndOfMonth().toEpochDay()-firstAvailable.toEpochDay()+1);for(int i=0;i<buckets.size();i++){List<User> bucket=buckets.get(i);User host=bucket.get(random.nextInt(bucket.size()));int startOffset=(int)Math.floor((double)i*availableDays/count);int endOffset=Math.max(startOffset,(int)Math.floor((double)(i+1)*availableDays/count)-1);int offset=startOffset+random.nextInt(endOffset-startOffset+1);LocalDate scheduledDate=firstAvailable.plusDays(Math.min(offset,availableDays-1));MeetingGroup g=new MeetingGroup();g.setChapter(chapter);g.setYear(ym.getYear());g.setMonth(ym.getMonthValue());g.setGroupNumber(i+1);g.setHost(host);g=groups.save(g);for(User u:bucket){MeetingParticipant p=new MeetingParticipant();p.setGroup(g);p.setMember(u);participants.save(p);}MonthlyMeeting m=new MonthlyMeeting();m.setGroup(g);m.setScheduledDate(scheduledDate);m.setScheduledTime(DEFAULT_TIME);meetings.save(m);for(User u:bucket)notifications.notify(u,"New monthly meeting","Group "+(i+1)+" meets on "+m.getScheduledDate()+" at "+m.getScheduledTime()+". "+host.getFullName()+" is the host; venue is awaiting host confirmation.");}}
 @Transactional(readOnly=true) public MeetingView mine(User user,YearMonth ym){MeetingParticipant p=participants.findByGroupYearAndGroupMonthAndMember(ym.getYear(),ym.getMonthValue(),user).orElseThrow(()->new EntityNotFoundException("No monthly meeting assigned"));return view(meetings.findByGroupId(p.getGroup().getId()).orElseThrow());}
 @Transactional(readOnly=true) public List<MeetingView> overview(Long chapterId,YearMonth ym){return meetings.findByGroupChapterIdAndGroupYearAndGroupMonthOrderByGroupGroupNumber(chapterId,ym.getYear(),ym.getMonthValue()).stream().map(this::view).toList();}
 @Transactional public MeetingView edit(Long id,User actor,UpdateRequest r,boolean admin){MonthlyMeeting m=meetings.findById(id).orElseThrow(()->new EntityNotFoundException("Meeting not found"));if(!admin&&!m.getGroup().getHost().getId().equals(actor.getId()))throw new SecurityException("Only the assigned host can edit this meeting");boolean detailsChange=r.date()!=null||r.time()!=null||r.venue()!=null;if(!admin&&detailsChange&&m.getEditCount()>=m.getMaxEdits())throw new SecurityException("Meeting edit limit reached");if(r.date()!=null){YearMonth meetingMonth=YearMonth.of(m.getGroup().getYear(),m.getGroup().getMonth());if(!YearMonth.from(r.date()).equals(meetingMonth))throw new IllegalArgumentException("Meeting date must remain in the assigned month");m.setScheduledDate(r.date());}if(r.time()!=null)m.setScheduledTime(r.time());if(r.venue()!=null)m.setVenue(r.venue().trim());if(r.status()!=null){if(!admin&&(r.status()==AutomatedMeetingStatus.COMPLETED||r.status()==AutomatedMeetingStatus.INCOMPLETE)&&LocalDate.now(ZoneId.of("Asia/Kolkata")).isBefore(m.getScheduledDate().plusDays(1)))throw new IllegalStateException("The host can submit the meeting outcome from the next day");m.setStatus(r.status());}if(!admin&&detailsChange)m.setEditCount(m.getEditCount()+1);MeetingView result=view(meetings.save(m));for(MeetingParticipant p:participants.findByGroupIdOrderByMemberFullNameAsc(m.getGroup().getId()))if(!p.getMember().getId().equals(actor.getId()))notifications.notify(p.getMember(),"Meeting updated","Your Group "+m.getGroup().getGroupNumber()+" meeting details changed.");return result;}
 @Transactional public CommentView comment(Long id,User actor,String text){MonthlyMeeting m=meetings.findById(id).orElseThrow(()->new EntityNotFoundException("Meeting not found"));if(!participants.existsByGroupIdAndMemberId(m.getGroup().getId(),actor.getId()))throw new SecurityException("Only group members can comment");if(text==null||text.isBlank())throw new IllegalArgumentException("Comment is required");MeetingComment c=new MeetingComment();c.setMeeting(m);c.setAuthor(actor);c.setText(text.trim());c=comments.save(c);if(!m.getGroup().getHost().getId().equals(actor.getId()))notifications.notify(m.getGroup().getHost(),"New meeting comment",actor.getFullName()+" commented on your group meeting.");return commentView(c);}
 private MeetingView view(MonthlyMeeting m){MeetingGroup g=m.getGroup();List<MemberView> ms=participants.findByGroupIdOrderByMemberFullNameAsc(g.getId()).stream().map(p->new MemberView(p.getMember().getId(),p.getMember().getFullName(),p.getMember().getProfileImage(),p.getMember().getBusinessName())).toList();List<CommentView> cs=comments.findByMeetingIdOrderByCreatedAtAsc(m.getId()).stream().map(this::commentView).toList();return new MeetingView(m.getId(),g.getId(),g.getGroupNumber(),g.getChapter().getId(),g.getChapter().getChapterName(),new MemberView(g.getHost().getId(),g.getHost().getFullName(),g.getHost().getProfileImage(),g.getHost().getBusinessName()),ms,m.getScheduledDate(),m.getScheduledTime(),m.getVenue(),m.getStatus(),m.getEditCount(),m.getMaxEdits(),cs);}
 private CommentView commentView(MeetingComment c){return new CommentView(c.getId(),c.getAuthor().getId(),c.getAuthor().getFullName(),c.getAuthor().getProfileImage(),c.getText(),c.getCreatedAt());}
 public record UpdateRequest(LocalDate date,LocalTime time,String venue,AutomatedMeetingStatus status){} public record MemberView(Long id,String name,String avatar,String businessName){} public record CommentView(Long id,Long authorId,String authorName,String avatar,String text,LocalDateTime createdAt){} public record MeetingView(Long id,Long groupId,int groupNumber,Long chapterId,String chapterName,MemberView host,List<MemberView> members,LocalDate date,LocalTime time,String venue,AutomatedMeetingStatus status,int editCount,int maxEdits,List<CommentView> comments){}
}
