package com.networkers.meetingautomation;
import com.networkers.common.ApiResponse; import com.networkers.security.CurrentUser; import com.networkers.user.*; import org.springframework.format.annotation.DateTimeFormat; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.IOException; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/monthly-meetings") public class MeetingAutomationController { private final MeetingAutomationService service; public MeetingAutomationController(MeetingAutomationService s){service=s;}
 @GetMapping("/cycle/mine") public ApiResponse<MeetingAutomationService.CycleDashboard> mineCycle(){return ApiResponse.ok("Face-to-face cycle",service.mineCycle(CurrentUser.get()));}
 @GetMapping("/admin/cycles/chapters/{chapterId}") public ApiResponse<MeetingAutomationService.CycleOverview> cycleOverview(@PathVariable Long chapterId){admin();return ApiResponse.ok("Face-to-face cycle",service.cycleOverview(chapterId));}
 @PostMapping({"/admin/cycles/chapters/{chapterId}/start","/admin/chapters/{chapterId}/cycles/start"}) public ApiResponse<MeetingAutomationService.CycleOverview> startCycle(@PathVariable Long chapterId){admin();return ApiResponse.ok("Face-to-face cycle started",service.startCycle(chapterId));}
 @PostMapping({"/admin/cycles/{cycleId}/regenerate","/admin/cycles/{cycleId}/restart"}) public ApiResponse<MeetingAutomationService.CycleOverview> regenerateCycle(@PathVariable Long cycleId){admin();return ApiResponse.ok("Face-to-face cycle restarted from today",service.regenerateCycle(cycleId));}
 @GetMapping("/mine") public ApiResponse<MeetingAutomationService.MeetingView> mine(@RequestParam(required=false) @DateTimeFormat(pattern="yyyy-MM") YearMonth month){return ApiResponse.ok("Face-to-face meeting",service.mine(CurrentUser.get(),month==null?YearMonth.now():month));}
 @PutMapping("/{id}") public ApiResponse<MeetingAutomationService.MeetingView> edit(@PathVariable Long id,@RequestBody MeetingAutomationService.UpdateRequest request){return ApiResponse.ok("Meeting updated",service.edit(id,CurrentUser.get(),request,false));}
 @PostMapping("/{id}/comments") public ApiResponse<MeetingAutomationService.CommentView> comment(@PathVariable Long id,@RequestBody CommentRequest request){return ApiResponse.ok("Comment posted",service.comment(id,CurrentUser.get(),request.text()));}
 @PostMapping(value="/{id}/pairs/{pairId}/complete",consumes="multipart/form-data") public ApiResponse<MeetingAutomationService.PairView> completePair(@PathVariable Long id,@PathVariable Long pairId,@RequestParam LocalDate metOn,@RequestParam String notes,@RequestPart MultipartFile photo) throws IOException{return ApiResponse.ok("One-to-one meeting completed and posted to Community Stories",service.completePair(id,pairId,CurrentUser.get(),metOn,notes,photo));}
 @GetMapping("/admin/chapters/{chapterId}") public ApiResponse<List<MeetingAutomationService.MeetingView>> overview(@PathVariable Long chapterId,@RequestParam(required=false) @DateTimeFormat(pattern="yyyy-MM") YearMonth month){admin();return ApiResponse.ok("Meeting groups",service.overview(chapterId,month==null?YearMonth.now():month));}
 @PostMapping("/admin/chapters/{chapterId}/regenerate") public ApiResponse<List<MeetingAutomationService.MeetingView>> regenerate(@PathVariable Long chapterId,@RequestParam(required=false) @DateTimeFormat(pattern="yyyy-MM") YearMonth month){admin();return ApiResponse.ok("Meeting groups regenerated",service.regenerate(chapterId,month==null?YearMonth.now():month));}
 @PutMapping("/admin/{id}") public ApiResponse<MeetingAutomationService.MeetingView> adminEdit(@PathVariable Long id,@RequestBody MeetingAutomationService.UpdateRequest request){admin();return ApiResponse.ok("Meeting overridden",service.edit(id,CurrentUser.get(),request,true));}
 @DeleteMapping("/admin/{id}") public ApiResponse<Boolean> deleteGroup(@PathVariable Long id){admin();service.deleteGroup(id);return ApiResponse.ok("Meeting group permanently deleted",true);}
 private void admin(){Role r=CurrentUser.get().getRole();if(r!=Role.ADMIN&&r!=Role.SUPER_ADMIN)throw new SecurityException("Admin access required");} public record CommentRequest(String text){}
}
