import {useEffect,useMemo,useState} from "react";
import {BellRing,CheckCircle2,Search} from "lucide-react";
import toast from "react-hot-toast";
import {eventFeeApi} from "../../api/eventFeeApi.js";

export default function EventFees(){
 const now=new Date();
 const[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState(now.getMonth()+1),[items,setItems]=useState([]),[query,setQuery]=useState(""),[paymentFilter,setPaymentFilter]=useState(""),[busy,setBusy]=useState(null),[bulkBusy,setBulkBusy]=useState(false);
 const load=()=>eventFeeApi.all(year,month).then(v=>setItems(v||[])).catch(()=>setItems([]));
 useEffect(()=>{setPaymentFilter("");setQuery("");load()},[year,month]);
 const unpaidCount=items.filter(i=>i.status==="UNPAID").length;
 const visible=useMemo(()=>items.filter(i=>{const matchesText=!query||`${i.memberName} ${i.email} ${i.mobile}`.toLowerCase().includes(query.toLowerCase());return matchesText&&(!paymentFilter||i.status===paymentFilter)}),[items,query,paymentFilter]);
 async function status(item,value){setBusy(item.id);try{await eventFeeApi.status(item.id,value);toast.success(value==="PAID"?"Member marked paid; reminders stopped for this month":"Member marked unpaid; reminders enabled");await load()}catch(e){toast.error(e.response?.data?.message||"Could not update status")}finally{setBusy(null)}}
 async function remind(item){setBusy(item.id);try{await eventFeeApi.remind(item.id);toast.success("Reminder sent to unpaid member");await load()}catch(e){toast.error(e.response?.data?.message||"Could not send reminder")}finally{setBusy(null)}}
 async function remindAll(){if(!unpaidCount)return toast("There are no unpaid members for this month");if(!window.confirm(`Send a payment reminder to all ${unpaidCount} unpaid members?`))return;setBulkBusy(true);try{const result=await eventFeeApi.remindUnpaid(year,month);toast.success(`Reminder sent to ${result?.notified??unpaidCount} unpaid member${unpaidCount===1?"":"s"}`);await load()}catch(e){toast.error(e.response?.data?.message||"Could not send reminders")}finally{setBulkBusy(false)}}
 return <div className="page-shell">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="page-kicker">Monthly collections</p><h1 className="page-title">Event <span className="text-brand-accent">Fees</span></h1><p className="mt-2 text-sm text-brand-muted">Every member starts each month as Unpaid for the ₹2,100 fee. Automatic reminders run from the 1st through the 7th and stop as soon as that month is marked Paid.</p></div><button className="btn-primary" disabled={bulkBusy||unpaidCount===0} onClick={remindAll}><BellRing size={17}/>{bulkBusy?"Sending...":`Remind all unpaid (${unpaidCount})`}</button></header>
  <section className="grid gap-4 sm:grid-cols-3"><Summary label="All members" value={items.length}/><Summary label="Paid" value={items.filter(i=>i.status==="PAID").length}/><Summary label="Unpaid" value={unpaidCount}/></section>
  <section className="card grid gap-3 p-4 md:grid-cols-4"><select aria-label="Month" className="field" value={month} onChange={e=>setMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2000,i).toLocaleString("en-IN",{month:"long"})}</option>)}</select><select aria-label="Year" className="field" value={year} onChange={e=>setYear(Number(e.target.value))}>{Array.from({length:6},(_,i)=>now.getFullYear()-i).map(y=><option key={y}>{y}</option>)}</select><select aria-label="Payment status" className="field" value={paymentFilter} onChange={e=>setPaymentFilter(e.target.value)}><option value="">All payment statuses</option><option value="PAID">Paid only</option><option value="UNPAID">Unpaid only</option></select><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-brand-muted" size={17}/><input className="field !pl-10" placeholder="Search member" value={query} onChange={e=>setQuery(e.target.value)}/></label></section>
  <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold text-brand-muted">Showing {visible.length} of {items.length} members</p>{(paymentFilter||query)&&<button className="btn-muted !min-h-9 !px-4 !py-1 text-xs" onClick={()=>{setPaymentFilter("");setQuery("")}}>Clear filters</button>}</div>
  <section className="card overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-red-500/10 text-xs uppercase text-red-500"><tr>{["Member","Contact","Month","Fee","Status","Last reminder","Actions"].map(h=><th className="p-4" key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(item=><tr className="border-t border-brand-border/15" key={item.id}><td className="p-4 font-bold">{item.memberName}</td><td className="p-4">{item.email}<p className="text-xs text-brand-muted">{item.mobile||"—"}</p></td><td className="p-4">{new Date(2000,item.month-1).toLocaleString("en-IN",{month:"long"})} {item.year}</td><td className="p-4 font-black text-red-500">₹{Number(item.amount).toLocaleString("en-IN")}</td><td className="p-4"><select className="field !w-32 !py-2" disabled={busy===item.id} value={item.status} onChange={e=>status(item,e.target.value)}><option value="UNPAID">Unpaid</option><option value="PAID">Paid</option></select></td><td className="p-4 text-brand-muted">{item.lastReminderDate||"Not sent"}</td><td className="p-4"><button className="btn-primary !px-3 !py-2" disabled={item.status==="PAID"||busy===item.id} onClick={()=>remind(item)}><BellRing size={16}/>Quick reminder</button></td></tr>)}{visible.length===0&&<tr><td colSpan="7" className="p-10 text-center text-brand-muted">No members match the selected filters.</td></tr>}</tbody></table></section>
 </div>
}
function Summary({label,value}){return <div className="glass-card rounded-3xl p-5"><CheckCircle2 className="text-red-500"/><p className="mt-3 text-3xl font-black">{value}</p><p className="text-xs font-bold uppercase text-brand-muted">{label}</p></div>}
