import {useEffect,useState} from "react";
import {CheckCircle2,QrCode,UserRoundPlus,X} from "lucide-react";
import {Link} from "react-router-dom";
import QRCode from "qrcode";
import toast from "react-hot-toast";
import VisitorForm,{emptyVisitor} from "../../components/admin/VisitorForm.jsx";
import {visitorApi} from "../../api/visitorApi.js";

export default function ManageVisitors(){const[form,setForm]=useState(emptyVisitor),[saving,setSaving]=useState(false),[payment,setPayment]=useState(null);async function submit(e){e.preventDefault();setSaving(true);try{const visitor=await visitorApi.create({...form,paymentAmount:Number(form.paymentAmount)});setForm({...emptyVisitor,visitDate:new Date().toISOString().slice(0,10)});setPayment(visitor);toast.success("Visitor saved. Complete payment confirmation.")}catch(error){toast.error(error.response?.data?.message||"Could not save visitor")}finally{setSaving(false)}}return <div className="page-shell"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="page-kicker">Front desk</p><h1 className="mt-1 page-title">Manage <span className="text-brand-accent">Visitors</span></h1><p className="mt-2 text-sm text-brand-muted">Register a visitor, collect the visit fee, and confirm payment.</p></div><Link className="btn-muted" to="/admin/visitors/details">View visitor details</Link></header><section className="grid gap-5 lg:grid-cols-[.35fr_1fr]"><div className="glass-card rounded-3xl p-6"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-red-500/10 text-red-500"><UserRoundPlus size={28}/></span><h2 className="mt-5 text-2xl font-black">New visitor</h2><p className="mt-2 text-sm leading-6 text-brand-muted">Enter the visitor and payment details. A payment QR will appear immediately after the record is saved.</p></div><VisitorForm form={form} setForm={setForm} onSubmit={submit} saving={saving} submitLabel="Save & show payment QR"/></section>{payment&&<PaymentModal visitor={payment} onClose={()=>setPayment(null)} onConfirmed={updated=>setPayment(updated)}/>}</div>}
function PaymentModal({visitor,onClose,onConfirmed}){const[src,setSrc]=useState(""),[confirming,setConfirming]=useState(false);useEffect(()=>{QRCode.toDataURL(`NETWORKERS|VISITOR:${visitor.id}|NAME:${visitor.fullName}|AMOUNT:${Number(visitor.paymentAmount||0).toFixed(2)}`,{width:320,margin:2,color:{dark:"#111111",light:"#ffffff"}}).then(setSrc)},[visitor.id,visitor.fullName,visitor.paymentAmount]);async function confirm(){setConfirming(true);try{const updated=await visitorApi.confirmPayment(visitor.id);onConfirmed(updated);toast.success("Payment confirmed successfully")}catch(error){toast.error(error.response?.data?.message||"Could not confirm payment")}finally{setConfirming(false)}}return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="card my-6 w-full max-w-md p-6 text-center"><div className="flex justify-end"><button className="glass-icon" onClick={onClose} aria-label="Close"><X/></button></div>{visitor.paymentConfirmed?<><CheckCircle2 className="mx-auto text-emerald-500" size={64}/><h2 className="mt-4 text-2xl font-black">Payment confirmed</h2><p className="mt-2 text-brand-muted">{visitor.fullName} is now registered as a paid visitor.</p><button className="btn-primary mt-6 w-full" onClick={onClose}>Done</button></>:<><QrCode className="mx-auto text-red-500"/><h2 className="mt-3 text-2xl font-black">Visitor payment</h2><p className="mt-1 text-sm text-brand-muted">Visitor #{visitor.id} · {visitor.fullName}</p><div className="mx-auto mt-5 w-fit rounded-3xl bg-white p-3 shadow-xl">{src?<img className="h-64 w-64" src={src} alt={`Payment QR for ${visitor.fullName}`}/>:<div className="h-64 w-64 animate-pulse rounded-xl bg-slate-200"/>}</div><p className="mt-5 text-3xl font-black text-red-500">Rs {Number(visitor.paymentAmount||0).toLocaleString("en-IN")}</p><button disabled={confirming} className="btn-primary mt-5 w-full" onClick={confirm}>{confirming?"Confirming...":"Payment confirmed"}</button></>}</div></div>}
